version: '3.3'

services:

  postgres:
    image: postgres
    restart: always
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints: [node.labels.db_role == postgresql]
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: "keycloak"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - keycloak

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: always
    depends_on:
      - postgres
    ports:
      - 8443:8443
    volumes:
      - .:/tmp
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: "postgres"
      DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      JDBC_PARAMS: "connectTimeout=30"
      DB_ADDR: "postgres"
      KEYCLOAK_IMPORT: /tmp/realm-export.json

    networks:
      - keycloak
      - proxy

networks:
  keycloak:
  proxy:
    external: true
