version: '3.5'

services:

  postgres:
    image: postgres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.db_role == postgresql]
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: "keycloak"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - keycloak

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    depends_on:
      - postgres
    ports:
      - 8443:8443
    volumes:
      - .:/tmp
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.node_role == devops]
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: "postgres"
      DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      JDBC_PARAMS: "connectTimeout=30"
      DB_ADDR: "postgres"
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:8443/auth/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s


    networks:
      - keycloak
      - proxy

networks:
  keycloak:
  proxy:
    external: true
