version: '3.5'
services:

  elasticsearch7-1:
    networks:
      - elasticsearch7-internal
    image: 'elasticsearch:7.8.1'
    command: [ 
      elasticsearch, 
      -E, network.host=0.0.0.0,
      -E, "cluster.initial_master_nodes=elasticsearch7-1,elasticsearch7-2,elasticsearch7-3",
      -E, "discovery.seed_hosts=elasticsearch7-1,elasticsearch7-2,elasticsearch7-3",
      -E, cluster.name=es7-cluster,
      -E, node.name=elasticsearch7-1
    ]
    volumes:
      - /home/ubuntu/es7data:/usr/share/elasticsearch/data
    environment:
      #https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
      ES_JAVA_OPTS: "-Xms4096m -Xmx4096m"
    deploy:
      mode: 'global'
      placement:
        constraints: [node.labels.es_placement == node_1]
      endpoint_mode: dnsrr

  elasticsearch7-2:
    networks:
      - elasticsearch7-internal
    image: 'elasticsearch:7.8.1'
    command: [
      elasticsearch,
      -E, network.host=0.0.0.0,
      -E, "cluster.initial_master_nodes=elasticsearch7-1,elasticsearch7-2,elasticsearch7-3",
      -E, "discovery.seed_hosts=elasticsearch7-1,elasticsearch7-2,elasticsearch7-3",
      -E, cluster.name=es7-cluster,
      -E, node.name=elasticsearch7-2
    ]
    volumes:
      - /home/ubuntu/es7data:/usr/share/elasticsearch/data
    environment:
      #https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
      ES_JAVA_OPTS: "-Xms4096m -Xmx4096m"
    deploy:
      mode: 'global'
      placement:
        constraints: [node.labels.es_placement == node_2]
      endpoint_mode: dnsrr

  elasticsearch7-3:
    networks:
      - elasticsearch7-internal
    image: 'elasticsearch:7.8.1'
    command: [
      elasticsearch,
      -E, network.host=0.0.0.0,
      -E, "cluster.initial_master_nodes=elasticsearch7-1,elasticsearch7-2,elasticsearch7-3",
      -E, "discovery.seed_hosts=elasticsearch7-1,elasticsearch7-2,elasticsearch7-3",
      -E, cluster.name=es7-cluster,
      -E, node.name=elasticsearch7-3
    ]
    volumes:
      - /home/ubuntu/es7data:/usr/share/elasticsearch/data
    environment:
      #https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
      ES_JAVA_OPTS: "-Xms4096m -Xmx4096m"
    deploy:
      mode: 'global'
      placement:
        constraints: [node.labels.es_placement == node_3]
      endpoint_mode: dnsrr

  elastic7:
    networks:
      - proxy
      - elasticsearch7-internal
    image: 'nginx:1'
    ports:
      - '9200:9200'
    deploy:
      placement:
        constraints: [node.labels.app_role == generic]
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    command: |
      /bin/bash -c "echo '
      client_max_body_size 0;
      
      upstream es7cluster {
          server elasticsearch7-1:9200;
          server elasticsearch7-2:9200;
          server elasticsearch7-3:9200;
      }

      server {
        listen 9200;
        add_header X-Frame-Options "SAMEORIGIN";
        location / {
            proxy_pass http://es7cluster;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
      }
      ' | tee /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  kibana7:
    image: kibana:7.8.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch7-1:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch7-1:9200 
    ports:
      - 5601:5601
    networks:
      - elasticsearch7-internal
    command: ["/usr/local/bin/kibana-docker"]
    deploy:
      placement:
        constraints: [node.labels.app_role == generic]
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:5601/status"]
    #  interval: 10s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 30s

networks:
  elasticsearch7-internal:
    external: true
  proxy:
    external: true
