- hosts: all

  vars:
    docker_edition: 'ce'
    docker_compose_version: "1.24.1"
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.docker
    - geerlingguy.pip