version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: "db"
    secrets:
      - db_password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8188:8080

secrets:
  db_password:
    file: ./POSTGRES_PASSWORD.txt