version: '3.2'
services:
  cellbase:
    image: mongo:latest
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    ports:
      - 27017:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.labels.app_role == generic
        - node.labels.state_anchor == true

volumes:
  db-data:
  mongo-config: