version: "3.3"

services:

  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
    networks:
      - proxy
    volumes:
      - redis-data:/data
networks:
  proxy:
    external: true

volumes:
  redis-data: